using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace ProtocolChecks;

/// <summary>
/// The text of a surface snapshot: one section per group, one line per type with its kind and bases, one indented
/// line per member at or above an accessibility floor, all ordinal. Rich enough that the change worth catching moves
/// a line: the kind of a type and its bases, <c>static</c>, constant and enum values, nullability, <c>ref</c>/<c>out</c>/
/// <c>in</c>/<c>params</c>, default values, and <c>init</c> as distinct from <c>set</c>. Shared by the public-surface
/// snapshot (<see cref="SurfaceTests"/>) and the tree-contract snapshot (<see cref="TreeContractSnapshotTests"/>).
/// </summary>
internal static class SurfaceText
{
    private static readonly NullabilityInfoContext NullabilityContext = new();

    /// <summary>The public-surface snapshot of the given assemblies, one section per assembly.</summary>
    public static string Describe(IReadOnlyList<Assembly> assemblies)
    {
        ArgumentNullException.ThrowIfNull(assemblies);
        var groups = assemblies.Select(assembly => (
            assembly.GetName().Name!,
            (IEnumerable<Type>)assembly.GetExportedTypes().OrderBy(type => type.FullName, StringComparer.Ordinal)));
        return DescribeTypes(
            [
                "# Public surface of the library assemblies of the tree.",
                "# Generated by the protocol tests (SurfaceTests); a tripwire, not a contract: the contract is the API.md of each node.",
                "# On an intended change, update that API.md and replace this file with PublicSurface.actual.txt in the same commit.",
            ],
            groups,
            MemberAccessibility.IsPublic);
    }

    /// <summary>The snapshot text of a set of type groups, each under its own <c>== header</c>, keeping the members
    /// <paramref name="included"/> accepts.</summary>
    public static string DescribeTypes(
        IReadOnlyList<string> comments, IEnumerable<(string Header, IEnumerable<Type> Types)> groups, Func<MemberInfo, bool> included)
    {
        ArgumentNullException.ThrowIfNull(comments);
        ArgumentNullException.ThrowIfNull(groups);
        var builder = new StringBuilder();
        foreach (var comment in comments)
        {
            _ = builder.AppendLine(comment);
        }

        foreach (var (header, types) in groups)
        {
            _ = builder.AppendLine();
            _ = builder.AppendLine("== " + header);
            foreach (var type in types)
            {
                _ = builder.AppendLine();
                _ = builder.AppendLine(DescribeType(type));
                var members = type.GetMembers(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                    .Where(member => included(member) && IsWorthListing(member))
                    .Select(member => MemberAccessibility.Prefix(member) + DescribeMember(type, member, included))
                    .Order(StringComparer.Ordinal);
                foreach (var member in members)
                {
                    _ = builder.AppendLine("    " + member);
                }
            }
        }

        return builder.ToString();
    }

    /// <summary>Line endings and trailing white space normalised, so a snapshot compares equal across platforms.</summary>
    public static string Normalise(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        return text.ReplaceLineEndings("\n").TrimEnd();
    }

    private static string DescribeType(Type type)
    {
        var kind = type.IsEnum ? "enum"
            : type.IsInterface ? "interface"
            : typeof(Delegate).IsAssignableFrom(type) ? "delegate"
            : type.IsValueType ? (type.IsDefined(typeof(IsReadOnlyAttribute), inherit: false) ? "readonly struct" : "struct")
            : type.IsAbstract && type.IsSealed ? "static class"
            : type.IsSealed ? "sealed class"
            : type.IsAbstract ? "abstract class"
            : "class";
        if (type.GetMethod("<Clone>$", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance) is not null
            || (type.IsValueType && type.GetMethod("PrintMembers", BindingFlags.NonPublic | BindingFlags.Instance) is { } print && TypeShape.IsCompilerGenerated(print)))
        {
            kind += " (record)";
        }

        var bases = new List<string>();
        if (type.BaseType is { } baseType && baseType != typeof(object) && baseType != typeof(ValueType) && baseType != typeof(Enum) && baseType != typeof(MulticastDelegate))
        {
            bases.Add(TypeName(baseType));
        }

        bases.AddRange(type.GetInterfaces().Where(contract => contract.IsPublic || contract.IsNestedPublic).Select(contract => TypeName(contract)).Order(StringComparer.Ordinal));
        var underlying = type.IsEnum ? " : " + TypeName(Enum.GetUnderlyingType(type)) : bases.Count > 0 ? " : " + string.Join(", ", bases) : string.Empty;
        return $"{kind} {type.FullName}{underlying}";
    }

    /// <summary>
    /// Drops what the compiler wrote rather than the author: property and event accessors (reported through the property
    /// or the event), the record clone helper, the backing field of an enum, and members marked compiler-generated (the
    /// synthesized equality and printing of records). Operators and <c>Deconstruct</c> stay: a caller can bind to them.
    /// </summary>
    private static bool IsWorthListing(MemberInfo member) => member switch
    {
        MethodInfo { IsSpecialName: true } method when method.Name.StartsWith("get_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("set_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("add_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("remove_", StringComparison.Ordinal) => false,
        MethodInfo { Name: "<Clone>$" } => false,
        FieldInfo { Name: "value__" } => false,
        _ => !TypeShape.IsCompilerGenerated(member),
    };

    private static string DescribeMember(Type owner, MemberInfo member, Func<MemberInfo, bool> included) => member switch
    {
        MethodInfo method =>
            $"{(method.IsStatic ? "static " : string.Empty)}{TypeName(method.ReturnType, Nullability(method.ReturnParameter))} {method.Name}" +
            $"{GenericArguments(method)}({string.Join(", ", method.GetParameters().Select(DescribeParameter))})",
        ConstructorInfo constructor =>
            $"{(constructor.IsStatic ? "static " : string.Empty)}.ctor({string.Join(", ", constructor.GetParameters().Select(DescribeParameter))})",
        PropertyInfo property =>
            $"{(property.GetAccessors(nonPublic: true).Any(accessor => accessor.IsStatic) ? "static " : string.Empty)}" +
            $"{TypeName(property.PropertyType, Nullability(property))} " +
            (property.GetIndexParameters() is { Length: > 0 } indices
                ? $"this[{string.Join(", ", indices.Select(DescribeParameter))}]"
                : property.Name) +
            $" {{ {Getter(property, included)}{Setter(property, included)}}}",
        FieldInfo field when owner.IsEnum && field.IsLiteral =>
            $"{field.Name} = {Constant(field.GetRawConstantValue(), Enum.GetUnderlyingType(owner))}",
        FieldInfo field when field.IsLiteral =>
            $"const {TypeName(field.FieldType)} {field.Name} = {Constant(field.GetRawConstantValue(), field.FieldType)}",
        FieldInfo field =>
            $"{(field.IsStatic ? "static " : string.Empty)}{(field.IsInitOnly ? "readonly " : string.Empty)}{TypeName(field.FieldType, Nullability(field))} {field.Name}",
        EventInfo @event => $"event {TypeName(@event.EventHandlerType!)} {@event.Name}",
        Type nested => $"nested {nested.Name}",
        _ => $"{member.MemberType} {member.Name}",
    };

    private static string DescribeParameter(ParameterInfo parameter)
    {
        var modifier = parameter.IsOut ? "out "
            : parameter.IsIn ? "in "
            : parameter.ParameterType.IsByRef ? "ref "
            : parameter.IsDefined(typeof(ParamArrayAttribute), inherit: false) ? "params "
            : string.Empty;
        var name = TypeName(parameter.ParameterType, Nullability(parameter));
        var @default = parameter.HasDefaultValue ? " = " + Constant(parameter.RawDefaultValue, parameter.ParameterType) : string.Empty;
        return $"{modifier}{name} {parameter.Name}{@default}";
    }

    private static string Getter(PropertyInfo property, Func<MemberInfo, bool> included) =>
        property.GetMethod is { } getter && included(getter) ? "get; " : string.Empty;

    /// <summary>Tells init from set: reflection reports both as writable, and the difference is the immutability a tree
    /// usually insists on.</summary>
    private static string Setter(PropertyInfo property, Func<MemberInfo, bool> included)
    {
        if (property.SetMethod is not { } setter || !included(setter))
        {
            return string.Empty;
        }

        var initOnly = setter.ReturnParameter.GetRequiredCustomModifiers().Any(modifier => modifier.FullName == "System.Runtime.CompilerServices.IsExternalInit");
        return initOnly ? "init; " : "set; ";
    }

    private static string GenericArguments(MethodInfo method) =>
        method.IsGenericMethod ? "<" + string.Join(", ", method.GetGenericArguments().Select(argument => argument.Name)) + ">" : string.Empty;

    private static bool Nullability(ParameterInfo parameter) => IsNullable(NullabilityContext.Create(parameter));

    private static bool Nullability(PropertyInfo property) => IsNullable(NullabilityContext.Create(property));

    private static bool Nullability(FieldInfo field) => IsNullable(NullabilityContext.Create(field));

    private static bool IsNullable(NullabilityInfo info) =>
        !info.Type.IsValueType && (info.ReadState == NullabilityState.Nullable || info.WriteState == NullabilityState.Nullable);

    /// <summary>C#-like names: generic arguments spelled out, arrays with brackets, nullable value types with a question
    /// mark, by-reference types as their element (the modifier is written by the parameter).</summary>
    private static string TypeName(Type type, bool nullable = false)
    {
        if (type.IsByRef || type.IsPointer)
        {
            return TypeName(type.GetElementType()!) + (type.IsPointer ? "*" : string.Empty);
        }

        if (type.IsArray)
        {
            return TypeName(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
        }

        if (Nullable.GetUnderlyingType(type) is { } underlying)
        {
            return TypeName(underlying) + "?";
        }

        var name = type.IsGenericType
            ? TypeShape.SimpleName(type) + "<" + string.Join(", ", type.GetGenericArguments().Select(argument => TypeName(argument))) + ">"
            : type.IsGenericParameter ? type.Name : TypeShape.SimpleName(type);
        if (type.IsNested && !type.IsGenericParameter)
        {
            name = TypeName(type.DeclaringType!) + "." + name;
        }

        return nullable ? name + "?" : name;
    }

    private static string Constant(object? value, Type type)
    {
        if (value is null)
        {
            return "null";
        }

        return type.IsEnum
            ? Enum.ToObject(type, value).ToString()!
            : value switch
            {
                string text => "\"" + text + "\"",
                bool flag => flag ? "true" : "false",
                double number => number.ToString("R", CultureInfo.InvariantCulture),
                float number => number.ToString("R", CultureInfo.InvariantCulture) + "f",
                IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
                _ => value.ToString() ?? "null",
            };
    }
}
